apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcu-device-plugin
  labels:
  {{- include "k8s-dcu-plugin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: dcu-dp-ds
    {{- include "k8s-dcu-plugin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: dcu-dp-ds
      {{- include "k8s-dcu-plugin.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hygon.com/dcu
                operator: In
                values:
                - "true"
              - key: dcu-mode
                operator: NotIn
                values:
                - mig
              - key: dcu
                operator: NotIn
                values:
                - "on"
      containers:
      - env:
        - name: PULSE
          value: {{ quote .Values.dcuDevicePlugin.dcuDpCntr.env.pulse }}
        - name: RESOURCE_REGISTER_STRATEGY
          value: {{ quote .Values.dcuDevicePlugin.dcuDpCntr.env.resourceRegisterStrategy
            }}
        - name: LOG_THRESHOLD
          value: {{ quote .Values.dcuDevicePlugin.dcuDpCntr.env.logThreshold }}
        - name: LOG_VERBOSE
          value: {{ quote .Values.dcuDevicePlugin.dcuDpCntr.env.logVerbose }}
        - name: LOG_OUTPUT
          value: {{ quote .Values.dcuDevicePlugin.dcuDpCntr.env.logOutput }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.dcuDevicePlugin.dcuDpCntr.image.repository }}:{{ .Values.dcuDevicePlugin.dcuDpCntr.image.tag
          | default .Chart.AppVersion }}
        name: dcu-dp-cntr
        resources: {}
        securityContext: {{- toYaml .Values.dcuDevicePlugin.dcuDpCntr.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins
          name: dp
        - mountPath: /dev
          name: dev
        - mountPath: /etc/vdev
          name: etc-vdev
          readOnly: true
        - mountPath: /opt/hyhal
          name: hyhal
          readOnly: true
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
        name: dp
      - hostPath:
          path: /etc/vdev
          type: DirectoryOrCreate
        name: etc-vdev
      - hostPath:
          path: /dev
        name: dev
      - hostPath:
          path: /opt/hyhal
        name: hyhal
