apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dcu-device-plugin
  labels:
  {{- include "k8s-dcu-plugin-hami.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: dcu-dp-ds-hami
    {{- include "k8s-dcu-plugin-hami.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: dcu-dp-ds-hami
      {{- include "k8s-dcu-plugin-hami.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: PULSE
          value: {{ quote .Values.dcuDevicePlugin.dcuDpCntr.env.pulse }}
        - name: RESOURCE_REGISTER_STRATEGY
          value: {{ quote .Values.dcuDevicePlugin.dcuDpCntr.env.resourceRegisterStrategy
            }}
        - name: LOG_THRESHOLD
          value: {{ quote .Values.dcuDevicePlugin.dcuDpCntr.env.logThreshold }}
        - name: LOG_VERBOSE
          value: {{ quote .Values.dcuDevicePlugin.dcuDpCntr.env.logVerbose }}
        - name: LOG_OUTPUT
          value: {{ quote .Values.dcuDevicePlugin.dcuDpCntr.env.logOutput }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.dcuDevicePlugin.dcuDpCntr.image.repository }}:{{ .Values.dcuDevicePlugin.dcuDpCntr.image.tag
          | default .Chart.AppVersion }}
        name: dcu-dp-cntr
        resources: {}
        securityContext: {{- toYaml .Values.dcuDevicePlugin.dcuDpCntr.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins
          name: dp
        - mountPath: /dev
          name: dev
        - mountPath: /etc/vdev
          name: etc-vdev
        - mountPath: /opt/hyhal
          name: hyhal
          readOnly: true
      nodeSelector: {{- toYaml .Values.dcuDevicePlugin.nodeSelector | nindent 8 }}
      serviceAccountName: dcu-device-plugin
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
        name: dp
      - hostPath:
          path: /etc/vdev
          type: DirectoryOrCreate
        name: etc-vdev
      - hostPath:
          path: /dev
        name: dev
      - hostPath:
          path: /opt/hyhal
        name: hyhal
